#!/usr/bin/env bash
set -euo pipefail

cur_version="$(<VERSION)"
cur_version="${cur_version#v}"

latest_tag="$(git tag --list | { grep -E '^v[0-9]+[.][0-9]+[.][0-9]+$' || true; } | sort -V | tail -1)"
latest_version="${latest_tag#v}"

if [[ -n "$latest_version" ]]; then
  if [[ "$cur_version" == "$latest_version" ]]; then
    :
  elif [[ "$(printf "%s\n%s\n" "$latest_version" "$cur_version" | sort -V | tail -1)" == "$cur_version" ]]; then
    echo "VERSION v$cur_version is newer than latest tag $latest_tag."
    echo "Release will be created by the release workflow when the PR is merged."
    exit 0
  else
    echo "VERSION v$cur_version is older than latest tag $latest_tag." >&2
    echo "Update VERSION or investigate the release state before continuing." >&2
    exit 1
  fi
fi

if [[ -n "$latest_tag" ]]; then
  commits_since_release="$(git rev-list "$latest_tag"..HEAD --count)"
  if [[ "$commits_since_release" -eq 0 ]]; then
    echo "No commits since last release $latest_tag"
    exit 0
  fi
  echo "Found $commits_since_release commits since $latest_tag"
fi

version="$(git cliff --bumped-version)"
changelog="$(git cliff --bump --unreleased | tail -n +2)"

if [[ "${DRY_RUN:-1}" == 1 ]]; then
  echo "version: $version"
  echo "changelog: $changelog"
  exit 0
fi

if [[ -z "$changelog" || "$changelog" == "<!-- generated by git-cliff -->" ]]; then
  echo "No unreleased changes found"
  exit 0
fi

actor_login="$(gh api user --jq .login)"
actor_id="$(gh api user --jq .id)"
git config user.name "$actor_login"
git config user.email "$actor_id+$actor_login@users.noreply.github.com"

# Configure git to use gh's credential helper. The checkout step uses
# persist-credentials: false, so the token is not written to .git/config.
gh auth setup-git

printf "%s\n" "${version#v}" >VERSION

git add VERSION
git status

git checkout -B release
git commit -m "chore: release $version"
git push origin release --force

if gh pr create --title "chore: release $version" --body "$changelog" --label "release"; then
  echo "Created new release PR"
else
  gh pr edit release --title "chore: release $version" --body "$changelog" --add-label "release"
  echo "Updated existing release PR"
fi
