#!/usr/bin/env bash
set -euo pipefail

: "${GITHUB_REPOSITORY:?GITHUB_REPOSITORY is required}"
: "${GH_TOKEN:?GH_TOKEN is required}"

CLOSE_AFTER_DAYS="${CLOSE_AFTER_DAYS:-7}"
DRY_RUN="${DRY_RUN:-false}"
IGNORED_AUTHOR="${IGNORED_AUTHOR:-jdx}"
IGNORED_LABEL="${IGNORED_LABEL:-keep-open}"
LIMIT="${LIMIT:-500}"
MAX_AGE_DAYS="${MAX_AGE_DAYS:-30}"
NOW="${NOW:-$(date -u +%Y-%m-%dT%H:%M:%SZ)}"
TODAY="${TODAY:-${NOW%%T*}}"
MARKER="<!-- pr-closer-warning"

if ! [[ "$CLOSE_AFTER_DAYS" =~ ^[0-9]+$ ]] || (( CLOSE_AFTER_DAYS < 1 )); then
  echo "close-after-days must be a positive integer" >&2
  exit 1
fi

if ! [[ "$MAX_AGE_DAYS" =~ ^[0-9]+$ ]] || (( MAX_AGE_DAYS < 1 )); then
  echo "max-age-days must be a positive integer" >&2
  exit 1
fi

if ! [[ "$LIMIT" =~ ^[0-9]+$ ]] || (( LIMIT < 1 )); then
  echo "limit must be a positive integer" >&2
  exit 1
fi

comment_pr() {
  local pr="$1"
  local body="$2"

  if [[ "$DRY_RUN" == "true" ]]; then
    echo "Would comment on PR #$pr:"
    echo "$body"
  else
    gh pr comment "$pr" -R "$GITHUB_REPOSITORY" --body "$body"
  fi
}

close_pr() {
  local pr="$1"
  local body="$2"

  if [[ "$DRY_RUN" == "true" ]]; then
    echo "Would close PR #$pr:"
    echo "$body"
  else
    gh pr close "$pr" -R "$GITHUB_REPOSITORY" -c "$body"
  fi
}

warn_or_close_broken_pr() {
  local pr="$1"
  local head_sha="$2"
  local reason="$3"

  comments=$(gh api "repos/$GITHUB_REPOSITORY/issues/$pr/comments" --paginate --slurp)
  warning_dates=$(jq -r --arg marker "$MARKER" --arg head_sha "$head_sha" '
    flatten
    | .[]
    | select(.body | contains($marker))
    | select(.body | contains("head_sha: " + $head_sha))
    | .body
    | capture("date: (?<date>[0-9]{4}-[0-9]{2}-[0-9]{2})")
    | .date
  ' <<< "$comments" | sort -u)

  warning_day=1
  if [[ -n "$warning_dates" ]]; then
    first_warning=$(head -n 1 <<< "$warning_dates")
    warning_day=$(( ($(date -u -d "$TODAY" +%s) - $(date -u -d "$first_warning" +%s)) / 86400 + 1 ))
  fi

  if (( warning_day > CLOSE_AFTER_DAYS )); then
    echo "Closing PR #$pr ($reason for $CLOSE_AFTER_DAYS days)"
    close_pr "$pr" "$(cat <<EOF
This PR has had $reason for more than $CLOSE_AFTER_DAYS days, so it is being closed automatically.

Feel free to reopen or create a new PR if you'd like to continue working on this.

*This comment was generated by an automated workflow.*
EOF
)"
    return
  fi

  if grep -qx "$TODAY" <<< "$warning_dates"; then
    echo "Already warned PR #$pr today ($reason)"
  else
    echo "Warning PR #$pr ($reason)"
    warning_status="This is warning day $warning_day of $CLOSE_AFTER_DAYS."
    if (( warning_day == CLOSE_AFTER_DAYS )); then
      warning_status="$warning_status This is the final warning before automatic closure."
    fi
    comment_pr "$pr" "$(cat <<EOF
This PR currently has $reason. If this continues for $CLOSE_AFTER_DAYS days, it will be closed automatically.

$warning_status

Please update the PR when you have a chance. Feel free to reopen or create a new PR if it is closed and you'd like to continue working on it.

*This comment was generated by an automated workflow.*

$MARKER
date: $TODAY
head_sha: $head_sha
-->
EOF
)"
  fi
}

close_old_pr() {
  local pr="$1"
  local created_at="$2"

  echo "Closing PR #$pr (created at $created_at, at least $MAX_AGE_DAYS full days old)"
  close_pr "$pr" "$(cat <<EOF
This PR has been open for at least $MAX_AGE_DAYS full days, so it is being closed automatically.

Please create a new PR if you'd like to continue working on this.

*This comment was generated by an automated workflow.*
EOF
)"
}

cutoff_epoch="$(date -u -d "$NOW -$MAX_AGE_DAYS days" +%s)"
pr_search="-author:$IGNORED_AUTHOR -label:$IGNORED_LABEL sort:updated-asc"

gh pr list \
  -R "$GITHUB_REPOSITORY" \
  --state open \
  --search "$pr_search" \
  --json number,mergeStateStatus,statusCheckRollup,headRefOid,createdAt \
  --limit "$LIMIT" | \
jq -r '
  def failed_check:
    (.statusCheckRollup | length > 0) and
    ([.statusCheckRollup[]? | (.conclusion // .state // "" | ascii_upcase)] | any(. == "FAILURE" or . == "ERROR" or . == "TIMED_OUT" or . == "ACTION_REQUIRED" or . == "STARTUP_FAILURE"));
  def pending_check:
    [.statusCheckRollup[]? | (.status // .state // "" | ascii_upcase)]
    | any(. == "QUEUED" or . == "IN_PROGRESS" or . == "WAITING" or . == "REQUESTED" or . == "PENDING" or . == "EXPECTED");

  .[]
  | failed_check as $failed
  | pending_check as $pending
  | (.mergeStateStatus == "DIRTY") as $conflicted
  | if $failed and $conflicted then [.number, .headRefOid, .createdAt, "broken", "failing checks and merge conflicts"]
    elif $failed then [.number, .headRefOid, .createdAt, "broken", "failing checks"]
    elif $conflicted then [.number, .headRefOid, .createdAt, "broken", "merge conflicts"]
    elif $pending then [.number, .headRefOid, .createdAt, "pending", "pending checks"]
    else [.number, .headRefOid, .createdAt, "healthy", ""]
    end
  | @tsv
' | \
while IFS=$'\t' read -r pr head_sha created_at state reason; do
  if [[ "$state" == "broken" ]]; then
    warn_or_close_broken_pr "$pr" "$head_sha" "$reason"
  elif [[ "$state" == "pending" ]]; then
    echo "Skipping PR #$pr because checks are still pending"
  elif (( $(date -u -d "$created_at" +%s) <= cutoff_epoch )); then
    close_old_pr "$pr" "$created_at"
  fi
done
