#!/usr/bin/env bash
set -euo pipefail

: "${GITHUB_REPOSITORY:?GITHUB_REPOSITORY is required}"
: "${GH_TOKEN:?GH_TOKEN is required}"

CLOSE_AFTER_DAYS="${CLOSE_AFTER_DAYS:-7}"
DRY_RUN="${DRY_RUN:-false}"
IGNORED_AUTHOR="${IGNORED_AUTHOR:-jdx}"
IGNORED_LABEL="${IGNORED_LABEL:-keep-open}"
LIMIT="${LIMIT:-500}"
TODAY="${TODAY:-$(date -u +%Y-%m-%d)}"
MARKER="<!-- pr-closer-warning"

if ! [[ "$CLOSE_AFTER_DAYS" =~ ^[0-9]+$ ]] || (( CLOSE_AFTER_DAYS < 1 )); then
  echo "close-after-days must be a positive integer" >&2
  exit 1
fi

if ! [[ "$LIMIT" =~ ^[0-9]+$ ]] || (( LIMIT < 1 )); then
  echo "limit must be a positive integer" >&2
  exit 1
fi

comment_pr() {
  local pr="$1"
  local body="$2"

  if [[ "$DRY_RUN" == "true" ]]; then
    echo "Would comment on PR #$pr:"
    echo "$body"
  else
    gh pr comment "$pr" -R "$GITHUB_REPOSITORY" --body "$body"
  fi
}

close_pr() {
  local pr="$1"
  local body="$2"

  if [[ "$DRY_RUN" == "true" ]]; then
    echo "Would close PR #$pr:"
    echo "$body"
  else
    gh pr close "$pr" -R "$GITHUB_REPOSITORY" -c "$body"
  fi
}

pr_search="-author:$IGNORED_AUTHOR -label:$IGNORED_LABEL sort:updated-asc"

gh pr list \
  -R "$GITHUB_REPOSITORY" \
  --state open \
  --search "$pr_search" \
  --json number,mergeStateStatus,statusCheckRollup,headRefOid \
  --limit "$LIMIT" | \
jq -r '
  def failed_check:
    (.statusCheckRollup | length > 0) and
    ([.statusCheckRollup[].conclusion // "" | ascii_upcase] | any(. == "FAILURE" or . == "TIMED_OUT" or . == "ACTION_REQUIRED" or . == "STARTUP_FAILURE"));

  .[]
  | failed_check as $failed
  | (.mergeStateStatus == "DIRTY") as $conflicted
  | if $failed and $conflicted then [.number, .headRefOid, "failing checks and merge conflicts"]
    elif $failed then [.number, .headRefOid, "failing checks"]
    elif $conflicted then [.number, .headRefOid, "merge conflicts"]
    else empty
    end
  | @tsv
' | \
while IFS=$'\t' read -r pr head_sha reason; do
  comments=$(gh api "repos/$GITHUB_REPOSITORY/issues/$pr/comments" --paginate --slurp)
  warning_dates=$(jq -r --arg marker "$MARKER" --arg head_sha "$head_sha" '
    flatten
    | .[]
    | select(.body | contains($marker))
    | select(.body | contains("head_sha: " + $head_sha))
    | .body
    | capture("date: (?<date>[0-9]{4}-[0-9]{2}-[0-9]{2})")
    | .date
  ' <<< "$comments" | sort -u)

  warning_days=0
  if [[ -n "$warning_dates" ]]; then
    yesterday=$(date -u -d "$TODAY - 1 day" +%Y-%m-%d)
    latest_warning=$(tail -n 1 <<< "$warning_dates")
    if [[ "$latest_warning" == "$TODAY" || "$latest_warning" == "$yesterday" ]]; then
      oldest_consecutive="$latest_warning"
      cursor="$latest_warning"
      while previous_day=$(date -u -d "$cursor - 1 day" +%Y-%m-%d); grep -qx "$previous_day" <<< "$warning_dates"; do
        oldest_consecutive="$previous_day"
        cursor="$previous_day"
      done
      warning_days=$(( ($(date -u -d "$latest_warning" +%s) - $(date -u -d "$oldest_consecutive" +%s)) / 86400 + 1 ))
    fi
  fi

  if (( warning_days >= CLOSE_AFTER_DAYS )); then
    echo "Closing PR #$pr ($reason for $warning_days consecutive warning days)"
    close_pr "$pr" "$(cat <<EOF
This PR has had $reason for $warning_days consecutive warning days, so it is being closed automatically.

Feel free to reopen or create a new PR if you'd like to continue working on this.

*This comment was generated by an automated workflow.*
EOF
)"
    continue
  fi

  if grep -qx "$TODAY" <<< "$warning_dates"; then
    echo "Already warned PR #$pr today ($reason)"
  else
    echo "Warning PR #$pr ($reason)"
    comment_pr "$pr" "$(cat <<EOF
This PR currently has $reason. If this continues for $CLOSE_AFTER_DAYS days, it will be closed automatically.

This is warning day $((warning_days + 1)) of $CLOSE_AFTER_DAYS.

Please update the PR when you have a chance. Feel free to reopen or create a new PR if it is closed and you'd like to continue working on it.

*This comment was generated by an automated workflow.*

$MARKER
date: $TODAY
head_sha: $head_sha
-->
EOF
)"
  fi
done
